/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the edsigmar.
 */
package es_optimasi;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Random;

/**
 *
 * @author UPEFATHIN
 */
public class FORM_ES extends javax.swing.JFrame {
    /**
     * Creates new form FORM_ES
     */
    double ix1,ix2, sigma1, sigma2, n1, n2,cx1, cx2;
    double[][] chromosome = new double[15][6];
    double[][] miu2 = new double[15][6];
    double[][] temp = new double[15][6];
    int M=1000, c1, c2, c3, x1, x2, ic1,ic2,ic3, ifx, fitness,
            fx1, fx2, k1x1, k1x2, k1y,
            k2x1, k2x2, k2y, k3x1, k3x2, k3y, m, n;
    Random random = new Random();
    DecimalFormat f = new DecimalFormat("##.##");
    
    public FORM_ES() {

        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension framesize = getSize();
        setLocation(
        (screenSize.width - framesize.width)/2,
        (screenSize.height - framesize.height)/2);
    } 

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Edsigmar.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jfx1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jfx2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jk1x1 = new javax.swing.JTextField();
        jk2x1 = new javax.swing.JTextField();
        jk3x1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jk1x2 = new javax.swing.JTextField();
        jk2x2 = new javax.swing.JTextField();
        jk3x2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jk1y = new javax.swing.JTextField();
        jk2y = new javax.swing.JTextField();
        jk3y = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jIterasi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextHasil = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evolutionary Strategies");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPTIMASI FUNGSI BERKENDALA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Maksimal fungsi ");

        jfx1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfx1.setText("400");

        jLabel3.setText("x1  +");

        jfx2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfx2.setText("500");

        jLabel5.setText("x2");

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kendala");

        jLabel7.setText("Kendala 1");

        jLabel8.setText("Kendala 2");

        jLabel9.setText("Kendala 3");

        jk1x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jk1x1.setText("10");

        jk2x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jk2x1.setText("9");

        jk3x1.setText("12");

        jLabel10.setText("x1  +");

        jLabel11.setText("x1  +");

        jLabel12.setText("x1  +");

        jk1x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jk1x2.setText("20");

        jk2x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jk2x2.setText("8");

        jk3x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jk3x2.setText("18");

        jLabel13.setText("x2   <=");

        jLabel14.setText("x2   <=");

        jLabel15.setText("x2   <=");

        jk1y.setText("350");

        jk2y.setText("200");

        jk3y.setText("300");

        jLabel4.setText("Jumlah Iterasi");

        jIterasi.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(199, 199, 199))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfx1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfx2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addComponent(jIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jk1x1)
                                    .addComponent(jk2x1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jk1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jk2x2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jk1y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jk2y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jk3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jk3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jk3y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jfx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jfx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jk1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jk1y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jk2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jk2y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jk3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jk3y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTextHasil.setColumns(20);
        jTextHasil.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextHasil.setRows(5);
        jScrollPane1.setViewportView(jTextHasil);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("EVOLUTIONARY STRATEGIES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        
        jTextHasil.setText(null);
        
        int pos6=jTextHasil.getCaretPosition();
        jTextHasil.insert("============================= EVOLUTIONARY STRATEGIES (ES) ==================================\n"
                + "LAMDA = 5, MIU = 2*LAMDA, (MIU + LAMDA)\n\nINISIALISASI\n", pos6);
        
        inisialisasi();
        m=Integer.parseInt(jIterasi.getText());
        for (n=0; n<m; n++){
            int pos=jTextHasil.getCaretPosition();
            jTextHasil.insert("Iterasi ke-"+(n+1)+"\n\n", pos);
            jTextHasil.insert("\n============================================================================================\n", pos);
        
            reproduksi();

            for (int i=0;i<15;i++){
                for (int j=0;j<6;j++){
                    int pos1=jTextHasil.getCaretPosition();
                    jTextHasil.insert(chromosome[i][j]+"\t", pos1);
                }
                int pos4=jTextHasil.getCaretPosition();
                jTextHasil.insert("\n", pos4);
            }

            sort(chromosome);

            for (int i=0;i<5;i++){
                for (int j=0;j<6;j++){
                    miu2[i][j]=chromosome[i][j];
                }
            }

            for (int i=0;i<15;i++){
                for (int j=0;j<6;j++){
                    chromosome[i][j]=temp[i][j];
                    chromosome[i][j]=miu2[i][j];
                }
            }

            int pos2=jTextHasil.getCaretPosition();
            jTextHasil.insert("\nGENERASI BARU\nx1\tx2\tsigma1\tsigma2\tf(x,y)\tfitness\n", pos2);
            
            for (int i=0;i<5;i++){
                for (int j=0;j<6;j++){
                    
                    int pos3=jTextHasil.getCaretPosition();
                    jTextHasil.insert(chromosome[i][j]+"\t", pos3);
                }
                int pos5=jTextHasil.getCaretPosition();
                jTextHasil.insert("\n", pos5);
            }
            int pos4=jTextHasil.getCaretPosition();
            jTextHasil.insert("\npupulasi terbaik: x1="+chromosome[0][0]+", x2="+chromosome[0][1]+", "
                    + "f(x,y)="+chromosome[0][4]+" dengan fitness="+chromosome[0][5]+"\n", pos4);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<edsigmar-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</edsigmar-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_ES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jIterasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextHasil;
    private javax.swing.JTextField jfx1;
    private javax.swing.JTextField jfx2;
    private javax.swing.JTextField jk1x1;
    private javax.swing.JTextField jk1x2;
    private javax.swing.JTextField jk1y;
    private javax.swing.JTextField jk2x1;
    private javax.swing.JTextField jk2x2;
    private javax.swing.JTextField jk2y;
    private javax.swing.JTextField jk3x1;
    private javax.swing.JTextField jk3x2;
    private javax.swing.JTextField jk3y;
    // End of variables declaration//GEN-END:variables

    public void inisialisasi (){
        int pos=jTextHasil.getCaretPosition();
        jTextHasil.insert("x1\tx2\tsigma1\tsigma2\tf(x,y)\troundx1\troundx2"
                + "\tc1\tc2\tc3\tfitness\n", pos);
        
        
        for (int i=0;i<5;i++){
            ix1 = Math.random()*50;
            ix2 = Math.random()*50;
            sigma1 = Math.random()*1;
            sigma2 = Math.random()*1;
            
            fitness();
            
            chromosome[i][0]=Double.valueOf(f.format(ix1));
            chromosome[i][1]=Double.valueOf(f.format(ix2));
            chromosome[i][2]=Double.valueOf(f.format(sigma1));
            chromosome[i][3]=Double.valueOf(f.format(sigma2));
            chromosome[i][4]=ifx;
            chromosome[i][5]=fitness;

            int pos1=jTextHasil.getCaretPosition();
            jTextHasil.insert(chromosome[i][0]+"\t"+chromosome[i][1]+"\t"
                    +chromosome[i][2]+"\t"+chromosome[i][3]+"\t"
                    +chromosome[i][4]+"\t"+x1+"\t"+x2+"\t"+c1+"\t"+c2+"\t"
                    + ""+c3+"\t"+chromosome[i][5]+"\n", pos1);
        }    
    }
    
    public void reproduksi(){
        int pos=jTextHasil.getCaretPosition();
        jTextHasil.insert("HASIL REPRODUKSI (MUTASI)\nx1\tx2\tsigma1\tsigma2"
                + "\tf(x,y)\tfitness\n", pos);
        
        for (int i=0;i<10;i++){
            n1 = random.nextGaussian();
            n2 = random.nextGaussian();
    
            int a=i/2;
            cx1 = chromosome[a][0] + (chromosome[a][2] * n1);
            cx2 = chromosome[a][1] + (chromosome[a][3] * n2);
            
            ix1 = cx1;
            ix2 = cx2;
            
            fitness();
            
            chromosome[i+5][0]=Double.valueOf(f.format(ix1));
            chromosome[i+5][1]=Double.valueOf(f.format(ix2));
            chromosome[i+5][4]=ifx;
            chromosome[i+5][5]=fitness;
            
            
            if (i%2==1) {
                if (chromosome[i+4][4] > chromosome[a][4] || 
                        chromosome[i+5][4] > chromosome[a][4]) {
                    sigma1 = chromosome[a][2] * 1.1;
                    sigma2 = chromosome[a][3] * 1.1;
                } else {
                    sigma1 = chromosome[a][2] * 0.9;
                    sigma2 = chromosome[a][3] * 0.9;
                }
                
                chromosome[i+4][2]=Double.valueOf(f.format(sigma1));
                chromosome[i+4][3]=Double.valueOf(f.format(sigma2));
                chromosome[i+5][2]=Double.valueOf(f.format(sigma1));
                chromosome[i+5][3]=Double.valueOf(f.format(sigma2));    
            }
        }           
    }
    
    public void fitness(){
        
        fx1 = Integer.parseInt(jfx1.getText());
        fx2 = Integer.parseInt(jfx2.getText());
        
        k1x1 = Integer.parseInt(jk1x1.getText());
        k1x2 = Integer.parseInt(jk1x2.getText());
        k1y = Integer.parseInt(jk1y.getText());
        
        k2x1 = Integer.parseInt(jk2x1.getText());
        k2x2 = Integer.parseInt(jk2x2.getText());
        k2y = Integer.parseInt(jk2y.getText());
        
        k3x1 = Integer.parseInt(jk3x1.getText());
        k3x2 = Integer.parseInt(jk3x2.getText());
        k3y = Integer.parseInt(jk3y.getText());
        
        x1 = (int) Math.round(ix1);
        x2 = (int) Math.round(ix2);
            
        ifx = (fx1 * x1) + (fx2 * x2);
            
        ic1 = (k1x1 * x1) + (k1x2 * x2);
        if (ic1 <= k1y){
            c1=0;
        } else {
            c1 = ic1 - k1y;
        }
        ic2 = (k2x1 * x1) + (k2x1 * x2);
        if (ic2 <= k2y){
            c2=0;
        } else {
            c2 = ic2 - k2y;
        }
            
        ic3 = (k3x1 * x1) + (k3x1 * x2);
        if (ic3 <= k3y){
            c3=0;
        } else {
            c3 = ic3 - k3y;
        }
            
        fitness = ifx - M * (c1+c2+c3);
    }
    
    public static void sort(double[][] ar) {
        Arrays.sort(ar, new Comparator<double[]>() {
            @Override
            public int compare(double[] int1, double[] int2) {
                double numOfKeys1 = int1[5];
                double numOfKeys2 = int2[5];
                return Double.compare(numOfKeys2, numOfKeys1);
            }
        });    
    }
}



